services:
  - type: web
    name: genai-pdf-assistant
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyCfLXqdvUysY-V9sS38UtypW5DtCVQqS7U
